name: Check Set-Up & Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set-Up
        run: sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl

      -  name: Install toolchain
         uses: actions-rs/toolchain@master
         with:
          profile: minimal
          components: rustfmt
          toolchain: nightly-2022-05-15
          target: wasm32-unknown-unknown

      - name: Check Build
        run: |
          SKIP_WASM_BUILD=1 cargo check --release

      - name: Run clippy
        run: | 
          rustup component add clippy --toolchain nightly-2022-05-15-x86_64-unknown-linux-gnu
          cargo clippy --all-targets --workspace -- --deny warnings

      - name: Unit tests
        run: cargo test --features runtime-benchmarks
